# config/logging.yaml

version: 1
formatters:
  default:
    format: "[%(asctime)s] [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO

  file:
    class: logging.FileHandler
    formatter: default
    filename: logs/system.log
    level: DEBUG

loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: false

  latency:
    handlers: [console, file]
    level: INFO
    propagate: false

  root:
    handlers: [console, file]
    level: DEBUG
